FROM python:3.8

# set a directory for the app
WORKDIR /usr/src/app

# copy all the files to the container
COPY . .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# define the port number the container should expose
EXPOSE 5000
EXPOSE 5010
EXPOSE 5020
EXPOSE 5030
EXPOSE 5040
EXPOSE 5050
EXPOSE 5060
EXPOSE 5070
EXPOSE 5080
EXPOSE 5090


# run the command
CMD ["python", "./app.py"]
